baseURL = 'https://san-tagoy.neocities.org/'
languageCode = 'en-us'
title = 'Getting Better'
theme = 'nostyleplease'
timeZone = 'Asia/Manila'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = true

[params]
  author = 'Nico Santagoy'
  images = '/feature.png'
  description = "I used to design games, now I write them. Am I a writer? I'd like to be one. I'd like to be many things, like a collage artist or a writer of Tabletop Role-playing Game content."
  favicon = '/favicon.ico'